In [1]:
import numpy as np


In [2]:
# **** create a numpy array with 5 values ****
a = np.random.rand(5)

print("a:\n", str(a))

# **** rank one array (not a row or a column vector) ***
print("a.shape: " + str(a.shape))

a:
 [0.59856595 0.03876    0.87998479 0.83277354 0.57358427]
a.shape: (5,)


In [3]:
print("a.T:\n" + str(a.T))
at = a.T;
print("at.shape: " + str(at.shape))

a.T:
[0.59856595 0.03876    0.87998479 0.83277354 0.57358427]
at.shape: (5,)


In [4]:
# **** should be a vector (returns a number)****
print("np.dot(a, at): " + str(np.dot(a, a.T)))

np.dot(a, at): 2.156667451097387


In [5]:
# **** instead use: ****
b = np.random.randn(5, 1)
print("b:\n" + str(b))
print("b.shape: " + str(b.shape))


b:
[[-0.16082202]
 [-0.59616096]
 [-0.14109024]
 [ 0.12482206]
 [-0.57974929]]
b.shape: (5, 1)


In [6]:
# **** ****
bt = b.T
print("bt: ", bt)
print("(bt).shape: " + str(bt.shape))

bt:  [[-0.16082202 -0.59616096 -0.14109024  0.12482206 -0.57974929]]
(bt).shape: (1, 5)


In [7]:
# **** ****
print("np.dot(b, bt):\n" + str(np.dot(b, bt)))

np.dot(b, bt):
[[ 0.02586372  0.09587581  0.02269042 -0.02007414  0.09323645]
 [ 0.09587581  0.3554079   0.08411249 -0.07441404  0.3456239 ]
 [ 0.02269042  0.08411249  0.01990646 -0.01761117  0.08179697]
 [-0.02007414 -0.07441404 -0.01761117  0.01558055 -0.0723655 ]
 [ 0.09323645  0.3456239   0.08179697 -0.0723655   0.33610924]]


In [8]:
# **** column vector ****
c = np.random.randn(5,1)
print("c:\n" + str(c))
print("c.shape: " + str(c.shape))
assert(c.shape == (5,1))

c:
[[ 0.78972441]
 [ 1.22054239]
 [-0.33353284]
 [ 1.14566886]
 [-0.86414905]]
c.shape: (5, 1)


In [9]:
# **** row vector ****
c = np.random.randn(1, 5)
print("c:\n" + str(c))
print("c.shape: " + str(c.shape))
assert(c.shape == (1,5))

c:
[[-1.46988785 -0.36645894 -0.03568687 -0.36432731 -0.02556531]]
c.shape: (1, 5)


In [10]:
# **** do NOT use ****
c = np.random.rand(5)
print("c:\n" + str(c))
print("c.shape: " + str(c.shape))


c:
[0.49527347 0.81801972 0.50069938 0.95502156 0.35153775]
c.shape: (5,)


In [11]:
# **** to make sure c has the expected shape *****
assert(c.shape == (5,1))

AssertionError: 

In [12]:
# **** you can also reshape an array ****
c = np.random.rand(6)
print("c.shape: " + str(c.shape))
print("c: " + str(c))
print()

c = c.reshape(1, 6)
print("c.shape: " + str(c.shape))
print("c: " + str(c))
print()

c = c.reshape(6, 1)
print("c.shape: " + str(c.shape))
print("c:\n" + str(c))

c.shape: (6,)
c: [0.0122801  0.8858489  0.13227552 0.65613547 0.94701376 0.99253127]

c.shape: (1, 6)
c: [[0.0122801  0.8858489  0.13227552 0.65613547 0.94701376 0.99253127]]

c.shape: (6, 1)
c:
[[0.0122801 ]
 [0.8858489 ]
 [0.13227552]
 [0.65613547]
 [0.94701376]
 [0.99253127]]
